# -*- coding:utf-8 -*-
from __future__ import unicode_literals

from django.utils.translation import ugettext_lazy as _

LANG_INFO = {
    'af': {
        'bidi': False,
        'code': 'af',
        'name': 'Afrikaans',
        'name_local': 'Afrikaans',
    },
    'ar': {
        'bidi': True,
        'code': 'ar',
        'name': 'Arabic',
        'name_local': 'العربيّة',
    },
    'ast': {
        'bidi': False,
        'code': 'ast',
        'name': 'Asturian',
        'name_local': 'asturianu',
    },
    'az': {
        'bidi': True,
        'code': 'az',
        'name': 'Azerbaijani',
        'name_local': 'Azərbaycanca',
    },
    'be': {
        'bidi': False,
        'code': 'be',
        'name': 'Belarusian',
        'name_local': 'беларуская',
    },
    'bg': {
        'bidi': False,
        'code': 'bg',
        'name': 'Bulgarian',
        'name_local': 'български',
    },
    'bn': {
        'bidi': False,
        'code': 'bn',
        'name': 'Bengali',
        'name_local': 'বাংলা',
    },
    'br': {
        'bidi': False,
        'code': 'br',
        'name': 'Breton',
        'name_local': 'brezhoneg',
    },
    'bs': {
        'bidi': False,
        'code': 'bs',
        'name': 'Bosnian',
        'name_local': 'bosanski',
    },
    'ca': {
        'bidi': False,
        'code': 'ca',
        'name': 'Catalan',
        'name_local': 'català',
    },
    'cs': {
        'bidi': False,
        'code': 'cs',
        'name': 'Czech',
        'name_local': 'česky',
    },
    'cy': {
        'bidi': False,
        'code': 'cy',
        'name': 'Welsh',
        'name_local': 'Cymraeg',
    },
    'da': {
        'bidi': False,
        'code': 'da',
        'name': 'Danish',
        'name_local': 'dansk',
    },
    'de': {
        'bidi': False,
        'code': 'de',
        'name': 'German',
        'name_local': 'Deutsch',
    },
    'dsb': {
        'bidi': False,
        'code': 'dsb',
        'name': 'Lower Sorbian',
        'name_local': 'dolnoserbski',
    },
    'el': {
        'bidi': False,
        'code': 'el',
        'name': 'Greek',
        'name_local': 'Ελληνικά',
    },
    'en': {
        'bidi': False,
        'code': 'en',
        'name': 'English',
        'name_local': 'English',
    },
    'en-au': {
        'bidi': False,
        'code': 'en-au',
        'name': 'Australian English',
        'name_local': 'Australian English',
    },
    'en-gb': {
        'bidi': False,
        'code': 'en-gb',
        'name': 'British English',
        'name_local': 'British English',
    },
    'eo': {
        'bidi': False,
        'code': 'eo',
        'name': 'Esperanto',
        'name_local': 'Esperanto',
    },
    'es': {
        'bidi': False,
        'code': 'es',
        'name': 'Spanish',
        'name_local': 'español',
    },
    'es-ar': {
        'bidi': False,
        'code': 'es-ar',
        'name': 'Argentinian Spanish',
        'name_local': 'español de Argentina',
    },
    'es-co': {
        'bidi': False,
        'code': 'es-co',
        'name': 'Colombian Spanish',
        'name_local': 'español de Colombia',
    },
    'es-mx': {
        'bidi': False,
        'code': 'es-mx',
        'name': 'Mexican Spanish',
        'name_local': 'español de Mexico',
    },
    'es-ni': {
        'bidi': False,
        'code': 'es-ni',
        'name': 'Nicaraguan Spanish',
        'name_local': 'español de Nicaragua',
    },
    'es-ve': {
        'bidi': False,
        'code': 'es-ve',
        'name': 'Venezuelan Spanish',
        'name_local': 'español de Venezuela',
    },
    'et': {
        'bidi': False,
        'code': 'et',
        'name': 'Estonian',
        'name_local': 'eesti',
    },
    'eu': {
        'bidi': False,
        'code': 'eu',
        'name': 'Basque',
        'name_local': 'Basque',
    },
    'fa': {
        'bidi': True,
        'code': 'fa',
        'name': 'Persian',
        'name_local': 'فارسی',
    },
    'fi': {
        'bidi': False,
        'code': 'fi',
        'name': 'Finnish',
        'name_local': 'suomi',
    },
    'fr': {
        'bidi': False,
        'code': 'fr',
        'name': 'French',
        'name_local': 'français',
    },
    'fy': {
        'bidi': False,
        'code': 'fy',
        'name': 'Frisian',
        'name_local': 'frysk',
    },
    'ga': {
        'bidi': False,
        'code': 'ga',
        'name': 'Irish',
        'name_local': 'Gaeilge',
    },
    'gd': {
        'bidi': False,
        'code': 'gd',
        'name': 'Scottish Gaelic',
        'name_local': 'Gàidhlig',
    },
    'gl': {
        'bidi': False,
        'code': 'gl',
        'name': 'Galician',
        'name_local': 'galego',
    },
    'he': {
        'bidi': True,
        'code': 'he',
        'name': 'Hebrew',
        'name_local': 'עברית',
    },
    'hi': {
        'bidi': False,
        'code': 'hi',
        'name': 'Hindi',
        'name_local': 'Hindi',
    },
    'hr': {
        'bidi': False,
        'code': 'hr',
        'name': 'Croatian',
        'name_local': 'Hrvatski',
    },
    'hsb': {
        'bidi': False,
        'code': 'hsb',
        'name': 'Upper Sorbian',
        'name_local': 'hornjoserbsce',
    },
    'hu': {
        'bidi': False,
        'code': 'hu',
        'name': 'Hungarian',
        'name_local': 'Magyar',
    },
    'ia': {
        'bidi': False,
        'code': 'ia',
        'name': 'Interlingua',
        'name_local': 'Interlingua',
    },
    'io': {
        'bidi': False,
        'code': 'io',
        'name': 'Ido',
        'name_local': 'ido',
    },
    'id': {
        'bidi': False,
        'code': 'id',
        'name': 'Indonesian',
        'name_local': 'Bahasa Indonesia',
    },
    'is': {
        'bidi': False,
        'code': 'is',
        'name': 'Icelandic',
        'name_local': 'Íslenska',
    },
    'it': {
        'bidi': False,
        'code': 'it',
        'name': 'Italian',
        'name_local': 'italiano',
    },
    'ja': {
        'bidi': False,
        'code': 'ja',
        'name': 'Japanese',
        'name_local': '日本語',
    },
    'ka': {
        'bidi': False,
        'code': 'ka',
        'name': 'Georgian',
        'name_local': 'ქართული',
    },
    'kk': {
        'bidi': False,
        'code': 'kk',
        'name': 'Kazakh',
        'name_local': 'Қазақ',
    },
    'km': {
        'bidi': False,
        'code': 'km',
        'name': 'Khmer',
        'name_local': 'Khmer',
    },
    'kn': {
        'bidi': False,
        'code': 'kn',
        'name': 'Kannada',
        'name_local': 'Kannada',
    },
    'ko': {
        'bidi': False,
        'code': 'ko',
        'name': 'Korean',
        'name_local': '한국어',
    },
    'lb': {
        'bidi': False,
        'code': 'lb',
        'name': 'Luxembourgish',
        'name_local': 'Lëtzebuergesch',
    },
    'lt': {
        'bidi': False,
        'code': 'lt',
        'name': 'Lithuanian',
        'name_local': 'Lietuviškai',
    },
    'lv': {
        'bidi': False,
        'code': 'lv',
        'name': 'Latvian',
        'name_local': 'latviešu',
    },
    'mk': {
        'bidi': False,
        'code': 'mk',
        'name': 'Macedonian',
        'name_local': 'Македонски',
    },
    'ml': {
        'bidi': False,
        'code': 'ml',
        'name': 'Malayalam',
        'name_local': 'Malayalam',
    },
    'mn': {
        'bidi': False,
        'code': 'mn',
        'name': 'Mongolian',
        'name_local': 'Mongolian',
    },
    'mr': {
        'bidi': False,
        'code': 'mr',
        'name': 'Marathi',
        'name_local': 'मराठी',
    },
    'my': {
        'bidi': False,
        'code': 'my',
        'name': 'Burmese',
        'name_local': 'မြန်မာဘာသာ',
    },
    'nb': {
        'bidi': False,
        'code': 'nb',
        'name': 'Norwegian Bokmal',
        'name_local': 'norsk (bokmål)',
    },
    'ne': {
        'bidi': False,
        'code': 'ne',
        'name': 'Nepali',
        'name_local': 'नेपाली',
    },
    'nl': {
        'bidi': False,
        'code': 'nl',
        'name': 'Dutch',
        'name_local': 'Nederlands',
    },
    'nn': {
        'bidi': False,
        'code': 'nn',
        'name': 'Norwegian Nynorsk',
        'name_local': 'norsk (nynorsk)',
    },
    'no': {
        'bidi': False,
        'code': 'no',
        'name': 'Norwegian',
        'name_local': 'norsk',
    },
    'os': {
        'bidi': False,
        'code': 'os',
        'name': 'Ossetic',
        'name_local': 'Ирон',
    },
    'pa': {
        'bidi': False,
        'code': 'pa',
        'name': 'Punjabi',
        'name_local': 'Punjabi',
    },
    'pl': {
        'bidi': False,
        'code': 'pl',
        'name': 'Polish',
        'name_local': 'polski',
    },
    'pt': {
        'bidi': False,
        'code': 'pt',
        'name': 'Portuguese',
        'name_local': 'Português',
    },
    'pt-br': {
        'bidi': False,
        'code': 'pt-br',
        'name': 'Brazilian Portuguese',
        'name_local': 'Português Brasileiro',
    },
    'ro': {
        'bidi': False,
        'code': 'ro',
        'name': 'Romanian',
        'name_local': 'Română',
    },
    'ru': {
        'bidi': False,
        'code': 'ru',
        'name': 'Russian',
        'name_local': 'Русский',
    },
    'sk': {
        'bidi': False,
        'code': 'sk',
        'name': 'Slovak',
        'name_local': 'Slovensky',
    },
    'sl': {
        'bidi': False,
        'code': 'sl',
        'name': 'Slovenian',
        'name_local': 'Slovenščina',
    },
    'sq': {
        'bidi': False,
        'code': 'sq',
        'name': 'Albanian',
        'name_local': 'shqip',
    },
    'sr': {
        'bidi': False,
        'code': 'sr',
        'name': 'Serbian',
        'name_local': 'српски',
    },
    'sr-latn': {
        'bidi': False,
        'code': 'sr-latn',
        'name': 'Serbian Latin',
        'name_local': 'srpski (latinica)',
    },
    'sv': {
        'bidi': False,
        'code': 'sv',
        'name': 'Swedish',
        'name_local': 'svenska',
    },
    'sw': {
        'bidi': False,
        'code': 'sw',
        'name': 'Swahili',
        'name_local': 'Kiswahili',
    },
    'ta': {
        'bidi': False,
        'code': 'ta',
        'name': 'Tamil',
        'name_local': 'தமிழ்',
    },
    'te': {
        'bidi': False,
        'code': 'te',
        'name': 'Telugu',
        'name_local': 'తెలుగు',
    },
    'th': {
        'bidi': False,
        'code': 'th',
        'name': 'Thai',
        'name_local': 'ภาษาไทย',
    },
    'tr': {
        'bidi': False,
        'code': 'tr',
        'name': 'Turkish',
        'name_local': 'Türkçe',
    },
    'tt': {
        'bidi': False,
        'code': 'tt',
        'name': 'Tatar',
        'name_local': 'Татарча',
    },
    'udm': {
        'bidi': False,
        'code': 'udm',
        'name': 'Udmurt',
        'name_local': 'Удмурт',
    },
    'uk': {
        'bidi': False,
        'code': 'uk',
        'name': 'Ukrainian',
        'name_local': 'Українська',
    },
    'ur': {
        'bidi': True,
        'code': 'ur',
        'name': 'Urdu',
        'name_local': 'اردو',
    },
    'vi': {
        'bidi': False,
        'code': 'vi',
        'name': 'Vietnamese',
        'name_local': 'Tiếng Việt',
    },
    'zh-cn': {
        'fallback': ['zh-hans'],
    },
    'zh-hans': {
        'bidi': False,
        'code': 'zh-hans',
        'name': 'Simplified Chinese',
        'name_local': '简体中文',
    },
    'zh-hant': {
        'bidi': False,
        'code': 'zh-hant',
        'name': 'Traditional Chinese',
        'name_local': '繁體中文',
    },
    'zh-hk': {
        'fallback': ['zh-hant'],
    },
    'zh-mo': {
        'fallback': ['zh-hant'],
    },
    'zh-my': {
        'fallback': ['zh-hans'],
    },
    'zh-sg': {
        'fallback': ['zh-hans'],
    },
    'zh-tw': {
        'fallback': ['zh-hant'],
    },
}

COUNTRIES = {
    "AF": _("Afghanistan"),
    "AX": _("Åland Islands"),
    "AL": _("Albania"),
    "DZ": _("Algeria"),
    "AS": _("American Samoa"),
    "AD": _("Andorra"),
    "AO": _("Angola"),
    "AI": _("Anguilla"),
    "AQ": _("Antarctica"),
    "AG": _("Antigua and Barbuda"),
    "AR": _("Argentina"),
    "AM": _("Armenia"),
    "AW": _("Aruba"),
    "AU": _("Australia"),
    "AT": _("Austria"),
    "AZ": _("Azerbaijan"),
    "BS": _("Bahamas"),
    "BH": _("Bahrain"),
    "BD": _("Bangladesh"),
    "BB": _("Barbados"),
    "BY": _("Belarus"),
    "BE": _("Belgium"),
    "BZ": _("Belize"),
    "BJ": _("Benin"),
    "BM": _("Bermuda"),
    "BT": _("Bhutan"),
    "BO": _("Bolivia (Plurinational State of)"),
    "BQ": _("Bonaire, Sint Eustatius and Saba"),
    "BA": _("Bosnia and Herzegovina"),
    "BW": _("Botswana"),
    "BV": _("Bouvet Island"),
    "BR": _("Brazil"),
    "IO": _("British Indian Ocean Territory"),
    "BN": _("Brunei Darussalam"),
    "BG": _("Bulgaria"),
    "BF": _("Burkina Faso"),
    "BI": _("Burundi"),
    "CV": _("Cabo Verde"),
    "KH": _("Cambodia"),
    "CM": _("Cameroon"),
    "CA": _("Canada"),
    "KY": _("Cayman Islands"),
    "CF": _("Central African Republic"),
    "TD": _("Chad"),
    "CL": _("Chile"),
    "CN": _("China"),
    "CX": _("Christmas Island"),
    "CC": _("Cocos (Keeling) Islands"),
    "CO": _("Colombia"),
    "KM": _("Comoros"),
    "CD": _("Congo (the Democratic Republic of the)"),
    "CG": _("Congo"),
    "CK": _("Cook Islands"),
    "CR": _("Costa Rica"),
    "CI": _("Côte d'Ivoire"),
    "HR": _("Croatia"),
    "CU": _("Cuba"),
    "CW": _("Curaçao"),
    "CY": _("Cyprus"),
    "CZ": _("Czech Republic"),
    "DK": _("Denmark"),
    "DJ": _("Djibouti"),
    "DM": _("Dominica"),
    "DO": _("Dominican Republic"),
    "EC": _("Ecuador"),
    "EG": _("Egypt"),
    "SV": _("El Salvador"),
    "GQ": _("Equatorial Guinea"),
    "ER": _("Eritrea"),
    "EE": _("Estonia"),
    "ET": _("Ethiopia"),
    "FK": _("Falkland Islands  [Malvinas]"),
    "FO": _("Faroe Islands"),
    "FJ": _("Fiji"),
    "FI": _("Finland"),
    "FR": _("France"),
    "GF": _("French Guiana"),
    "PF": _("French Polynesia"),
    "TF": _("French Southern Territories"),
    "GA": _("Gabon"),
    "GM": _("Gambia"),
    "GE": _("Georgia"),
    "DE": _("Germany"),
    "GH": _("Ghana"),
    "GI": _("Gibraltar"),
    "GR": _("Greece"),
    "GL": _("Greenland"),
    "GD": _("Grenada"),
    "GP": _("Guadeloupe"),
    "GU": _("Guam"),
    "GT": _("Guatemala"),
    "GG": _("Guernsey"),
    "GN": _("Guinea"),
    "GW": _("Guinea-Bissau"),
    "GY": _("Guyana"),
    "HT": _("Haiti"),
    "HM": _("Heard Island and McDonald Islands"),
    "VA": _("Holy See"),
    "HN": _("Honduras"),
    "HK": _("Hong Kong"),
    "HU": _("Hungary"),
    "IS": _("Iceland"),
    "IN": _("India"),
    "ID": _("Indonesia"),
    "IR": _("Iran (Islamic Republic of)"),
    "IQ": _("Iraq"),
    "IE": _("Ireland"),
    "IM": _("Isle of Man"),
    "IL": _("Israel"),
    "IT": _("Italy"),
    "JM": _("Jamaica"),
    "JP": _("Japan"),
    "JE": _("Jersey"),
    "JO": _("Jordan"),
    "KZ": _("Kazakhstan"),
    "KE": _("Kenya"),
    "KI": _("Kiribati"),
    "KP": _("Korea (the Democratic People's Republic of)"),
    "KR": _("Korea (the Republic of)"),
    "KW": _("Kuwait"),
    "KG": _("Kyrgyzstan"),
    "LA": _("Lao People's Democratic Republic"),
    "LV": _("Latvia"),
    "LB": _("Lebanon"),
    "LS": _("Lesotho"),
    "LR": _("Liberia"),
    "LY": _("Libya"),
    "LI": _("Liechtenstein"),
    "LT": _("Lithuania"),
    "LU": _("Luxembourg"),
    "MO": _("Macao"),
    "MK": _("Macedonia (the former Yugoslav Republic of)"),
    "MG": _("Madagascar"),
    "MW": _("Malawi"),
    "MY": _("Malaysia"),
    "MV": _("Maldives"),
    "ML": _("Mali"),
    "MT": _("Malta"),
    "MH": _("Marshall Islands"),
    "MQ": _("Martinique"),
    "MR": _("Mauritania"),
    "MU": _("Mauritius"),
    "YT": _("Mayotte"),
    "MX": _("Mexico"),
    "FM": _("Micronesia (Federated States of)"),
    "MD": _("Moldova (the Republic of)"),
    "MC": _("Monaco"),
    "MN": _("Mongolia"),
    "ME": _("Montenegro"),
    "MS": _("Montserrat"),
    "MA": _("Morocco"),
    "MZ": _("Mozambique"),
    "MM": _("Myanmar"),
    "NA": _("Namibia"),
    "NR": _("Nauru"),
    "NP": _("Nepal"),
    "NL": _("Netherlands"),
    "NC": _("New Caledonia"),
    "NZ": _("New Zealand"),
    "NI": _("Nicaragua"),
    "NE": _("Niger"),
    "NG": _("Nigeria"),
    "NU": _("Niue"),
    "NF": _("Norfolk Island"),
    "MP": _("Northern Mariana Islands"),
    "NO": _("Norway"),
    "OM": _("Oman"),
    "PK": _("Pakistan"),
    "PW": _("Palau"),
    "PS": _("Palestine, State of"),
    "PA": _("Panama"),
    "PG": _("Papua New Guinea"),
    "PY": _("Paraguay"),
    "PE": _("Peru"),
    "PH": _("Philippines"),
    "PN": _("Pitcairn"),
    "PL": _("Poland"),
    "PT": _("Portugal"),
    "PR": _("Puerto Rico"),
    "QA": _("Qatar"),
    "RE": _("Réunion"),
    "RO": _("Romania"),
    "RU": _("Russian Federation"),
    "RW": _("Rwanda"),
    "BL": _("Saint Barthélemy"),
    "SH": _("Saint Helena, Ascension and Tristan da Cunha"),
    "KN": _("Saint Kitts and Nevis"),
    "LC": _("Saint Lucia"),
    "MF": _("Saint Martin (French part)"),
    "PM": _("Saint Pierre and Miquelon"),
    "VC": _("Saint Vincent and the Grenadines"),
    "WS": _("Samoa"),
    "SM": _("San Marino"),
    "ST": _("Sao Tome and Principe"),
    "SA": _("Saudi Arabia"),
    "SN": _("Senegal"),
    "RS": _("Serbia"),
    "SC": _("Seychelles"),
    "SL": _("Sierra Leone"),
    "SG": _("Singapore"),
    "SX": _("Sint Maarten (Dutch part)"),
    "SK": _("Slovakia"),
    "SI": _("Slovenia"),
    "SB": _("Solomon Islands"),
    "SO": _("Somalia"),
    "ZA": _("South Africa"),
    "GS": _("South Georgia and the South Sandwich Islands"),
    "SS": _("South Sudan"),
    "ES": _("Spain"),
    "LK": _("Sri Lanka"),
    "SD": _("Sudan"),
    "SR": _("Suriname"),
    "SJ": _("Svalbard and Jan Mayen"),
    "SZ": _("Swaziland"),
    "SE": _("Sweden"),
    "CH": _("Switzerland"),
    "SY": _("Syrian Arab Republic"),
    "TW": _("Taiwan (Province of China)"),
    "TJ": _("Tajikistan"),
    "TZ": _("Tanzania, United Republic of"),
    "TH": _("Thailand"),
    "TL": _("Timor-Leste"),
    "TG": _("Togo"),
    "TK": _("Tokelau"),
    "TO": _("Tonga"),
    "TT": _("Trinidad and Tobago"),
    "TN": _("Tunisia"),
    "TR": _("Turkey"),
    "TM": _("Turkmenistan"),
    "TC": _("Turks and Caicos Islands"),
    "TV": _("Tuvalu"),
    "UG": _("Uganda"),
    "UA": _("Ukraine"),
    "AE": _("United Arab Emirates"),
    "GB": _("United Kingdom of Great Britain and Northern Ireland"),
    "UM": _("United States Minor Outlying Islands"),
    "US": _("United States of America"),
    "UY": _("Uruguay"),
    "UZ": _("Uzbekistan"),
    "VU": _("Vanuatu"),
    "VE": _("Venezuela (Bolivarian Republic of)"),
    "VN": _("Viet Nam"),
    "VG": _("Virgin Islands (British)"),
    "VI": _("Virgin Islands (U.S.)"),
    "WF": _("Wallis and Futuna"),
    "EH": _("Western Sahara"),
    "YE": _("Yemen"),
    "ZM": _("Zambia"),
    "ZW": _("Zimbabwe"),
}

LANGUAGES = (
    ('af', _(u"Afrikaans")),
    ('ar', _(u"Arabic")),
    ('ast', _(u"Asturian")),
    ('az', _(u"Azerbaijani")),
    ('be', _(u"Belarusian")),
    ('bg', _(u"Bulgarian")),
    ('bn', _(u"Bengali")),
    ('br', _(u"Breton")),
    ('bs', _(u"Bosnian")),
    ('ca', _(u"Catalan")),
    ('cs', _(u"Czech")),
    ('cy', _(u"Welsh")),
    ('da', _(u"Danish")),
    ('de', _(u"German")),
    ('dsb', _(u"Lower Sorbian")),
    ('el', _(u"Greek")),
    ('en', _(u"English")),
    ('en-au', _(u"Australian English")),
    ('en-gb', _(u"British English")),
    ('eo', _(u"Esperanto")),
    ('es', _(u"Spanish")),
    ('es-ar', _(u"Argentinian Spanish")),
    ('es-co', _(u"Colombian Spanish")),
    ('es-mx', _(u"Mexican Spanish")),
    ('es-ni', _(u"Nicaraguan Spanish")),
    ('es-ve', _(u"Venezuelan Spanish")),
    ('et', _(u"Estonian")),
    ('eu', _(u"Basque")),
    ('fa', _(u"Persian")),
    ('fi', _(u"Finnish")),
    ('fr', _(u"French")),
    ('fy', _(u"Frisian")),
    ('ga', _(u"Irish")),
    ('gd', _(u"Scottish Gaelic")),
    ('gl', _(u"Galician")),
    ('he', _(u"Hebrew")),
    ('hi', _(u"Hindi")),
    ('hr', _(u"Croatian")),
    ('hsb', _(u"Upper Sorbian")),
    ('hu', _(u"Hungarian")),
    ('ia', _(u"Interlingua")),
    ('id', _(u"Indonesian")),
    ('io', _(u"Ido")),
    ('is', _(u"Icelandic")),
    ('it', _(u"Italian")),
    ('ja', _(u"Japanese")),
    ('ka', _(u"Georgian")),
    ('kk', _(u"Kazakh")),
    ('km', _(u"Khmer")),
    ('kn', _(u"Kannada")),
    ('ko', _(u"Korean")),
    ('lb', _(u"Luxembourgish")),
    ('lt', _(u"Lithuanian")),
    ('lv', _(u"Latvian")),
    ('mk', _(u"Macedonian")),
    ('ml', _(u"Malayalam")),
    ('mn', _(u"Mongolian")),
    ('mr', _(u"Marathi")),
    ('my', _(u"Burmese")),
    ('nb', _(u"Norwegian Bokmal")),
    ('ne', _(u"Nepali")),
    ('nl', _(u"Dutch")),
    ('nn', _(u"Norwegian Nynorsk")),
    ('no', _(u"Norwegian")),
    ('os', _(u"Ossetic")),
    ('pa', _(u"Punjabi")),
    ('pl', _(u"Polish")),
    ('pt', _(u"Portuguese")),
    ('pt-br', _(u"Brazilian Portuguese")),
    ('ro', _(u"Romanian")),
    ('ru', _(u"Russian")),
    ('sk', _(u"Slovak")),
    ('sl', _(u"Slovenian")),
    ('sq', _(u"Albanian")),
    ('sr', _(u"Serbian")),
    ('sr-latn', _(u"Serbian Latin")),
    ('sv', _(u"Swedish")),
    ('sw', _(u"Swahili")),
    ('ta', _(u"Tamil")),
    ('te', _(u"Telugu")),
    ('th', _(u"Thai")),
    ('tr', _(u"Turkish")),
    ('tt', _(u"Tatar")),
    ('udm', _(u"Udmurt")),
    ('uk', _(u"Ukrainian")),
    ('ur', _(u"Urdu")),
    ('vi', _(u"Vietnamese")),
    ('zh-cn', _(u"Simplified Chinese")),
    ('zh-hans', _(u"Simplified Chinese")),
    ('zh-hant', _(u"Traditional Chinese")),
    ('zh-hk', _(u"Traditional Chinese")),
    ('zh-mo', _(u"Traditional Chinese")),
    ('zh-my', _(u"Simplified Chinese")),
    ('zh-sg', _(u"Simplified Chinese")),
    ('zh-tw', _(u"Traditional Chinese"))
)

COUNTRIES_C = {
    "AF": _("阿富汗"),
    "AX": _("阿兰群岛"),
    "AL": _("阿尔巴尼亚"),
    "DZ": _("阿尔及利亚"),
    "AS": _("美属萨摩亚"),
    "AD": _("安道尔"),
    "AO": _("安哥拉"),
    "AI": _("安圭拉岛"),
    "AQ": _("南极洲"),
    "AG": _("安提瓜和巴布达"),
    "AR": _("阿根廷"),
    "AM": _("亚美尼亚"),
    "AW": _("阿鲁巴岛"),
    "AU": _("澳大利亚"),
    "AT": _("奥地利"),
    "AZ": _("阿塞拜疆"),
    "BS": _("巴哈马群岛"),
    "BH": _("巴林"),
    "BD": _("孟加拉国"),
    "BB": _("巴巴多斯"),
    "BY": _("白俄罗斯"),
    "BE": _("比利时"),
    "BZ": _("伯利兹"),
    "BJ": _("贝宁"),
    "BM": _("百慕大"),
    "BT": _("不丹"),
    "BO": _("玻利维亚多民族国"),
    "BQ": _("博内尔岛"),
    "BA": _("波斯尼亚和黑塞哥维那"),
    "BW": _("博茨瓦纳"),
    "BV": _("布维岛"),
    "BR": _("巴西"),
    "IO": _("英属印度洋领地"),
    "BN": _("文莱达鲁萨兰国"),
    "BG": _("保加利亚"),
    "BF": _("布基纳法索"),
    "BI": _("布隆迪"),
    "CV": _("佛得角"),
    "KH": _("柬埔寨"),
    "CM": _("喀麦隆"),
    "CA": _("加拿大"),
    "KY": _("开曼群岛"),
    "CF": _("中非共和国"),
    "TD": _("乍得"),
    "CL": _("智利"),
    "CN": _("中国"),
    "CX": _("圣诞岛"),
    "CC": _("科科斯(基林)群岛"),
    "CO": _("哥伦比亚"),
    "KM": _("科摩罗"),
    "CD": _("刚果民主共和国"),
    "CG": _("刚果"),
    "CK": _("库克群岛"),
    "CR": _("哥斯达黎加"),
    "CI": _("科特迪瓦"),
    "HR": _("克罗地亚"),
    "CU": _("古巴"),
    "CW": _("库拉索岛"),
    "CY": _("塞浦路斯"),
    "CZ": _("捷克共和国"),
    "DK": _("丹麦"),
    "DJ": _("吉布提"),
    "DM": _("多米尼加"),
    "DO": _("多米尼加共和国"),
    "EC": _("厄瓜多尔"),
    "EG": _("埃及"),
    "SV": _("萨尔瓦多"),
    "GQ": _("赤道几内亚"),
    "ER": _("厄立特里亚"),
    "EE": _("爱沙尼亚"),
    "ET": _("埃塞俄比亚"),
    "FK": _("福克兰群岛[马尔维纳斯]"),
    "FO": _("法罗群岛"),
    "FJ": _("斐济"),
    "FI": _("芬兰"),
    "FR": _("法国"),
    "GF": _("法属圭亚那"),
    "PF": _("法属波利尼西亚"),
    "TF": _("法属南部领地"),
    "GA": _("加蓬"),
    "GM": _("冈比亚"),
    "GE": _("格鲁吉亚"),
    "DE": _("德国"),
    "GH": _("加纳"),
    "GI": _("直布罗陀"),
    "GR": _("希腊"),
    "GL": _("格陵兰"),
    "GD": _("格林纳达"),
    "GP": _("瓜德罗普岛"),
    "GU": _("关岛"),
    "GT": _("危地马拉"),
    "GG": _("格恩西岛"),
    "GN": _("几内亚"),
    "GW": _("几内亚比绍"),
    "GY": _("圭亚那"),
    "HT": _("海地"),
    "HM": _("海德岛和麦克唐纳群岛"),
    "VA": _("罗马教廷"),
    "HN": _("洪都拉斯"),
    "HK": _("香港"),
    "HU": _("匈牙利"),
    "IS": _("冰岛"),
    "IN": _("印度"),
    "ID": _("印度尼西亚"),
    "IR": _("伊朗伊斯兰共和国"),
    "IQ": _("伊拉克"),
    "IE": _("爱尔兰"),
    "IM": _("马恩岛"),
    "IL": _("以色列"),
    "IT": _("意大利"),
    "JM": _("牙买加"),
    "JP": _("日本"),
    "JE": _("泽西岛"),
    "JO": _("约旦"),
    "KZ": _("哈萨克斯坦"),
    "KE": _("肯尼亚"),
    "KI": _("基里巴斯"),
    "KP": _("朝鲜民主主义人民共和国"),
    "KR": _("韩国(共和国)"),
    "KW": _("科威特"),
    "KG": _("吉尔吉斯斯坦"),
    "LA": _("老挝人民民主共和国"),
    "LV": _("拉脱维亚"),
    "LB": _("黎巴嫩"),
    "LS": _("莱索托"),
    "LR": _("利比里亚"),
    "LY": _("利比亚"),
    "LI": _("列支敦士登"),
    "LT": _("立陶宛"),
    "LU": _("卢森堡"),
    "MO": _("澳门"),
    "MK": _("马其顿(前南斯拉夫的共和国)"),
    "MG": _("马达加斯加"),
    "MW": _("马拉维"),
    "MY": _("马来西亚"),
    "MV": _("马尔代夫"),
    "ML": _("马里"),
    "MT": _("马耳他"),
    "MH": _("马绍尔群岛"),
    "MQ": _("马提尼克岛"),
    "MR": _("毛里塔尼亚"),
    "MU": _("毛里求斯"),
    "YT": _("马约特岛"),
    "MX": _("墨西哥"),
    "FM": _("密克罗尼西亚联邦"),
    "MD": _("摩尔多瓦共和国"),
    "MC": _("摩纳哥"),
    "MN": _("蒙古"),
    "ME": _("黑山"),
    "MS": _("蒙特塞拉特"),
    "MA": _("摩洛哥"),
    "MZ": _("莫桑比克"),
    "MM": _("缅甸"),
    "NA": _("纳米比亚"),
    "NR": _("瑙鲁"),
    "NP": _("尼泊尔"),
    "NL": _("荷兰"),
    "NC": _("新加勒多尼亚"),
    "NZ": _("新西兰"),
    "NI": _("尼加拉瓜"),
    "NE": _("尼日尔"),
    "NG": _("尼日利亚"),
    "NU": _("纽埃岛"),
    "NF": _("诺福克岛"),
    "MP": _("北马里亚纳群岛"),
    "NO": _("挪威"),
    "OM": _("阿曼"),
    "PK": _("巴基斯坦"),
    "PW": _("帕劳"),
    "PS": _("巴勒斯坦"),
    "PA": _("巴拿马"),
    "PG": _("巴布亚新几内亚"),
    "PY": _("巴拉圭"),
    "PE": _("秘鲁"),
    "PH": _("菲律宾"),
    "PN": _("皮特凯恩群岛"),
    "PL": _("波兰"),
    "PT": _("葡萄牙"),
    "PR": _("波多黎各"),
    "QA": _("卡塔尔"),
    "RE": _("留尼汪"),
    "RO": _("罗马尼亚"),
    "RU": _("俄罗斯联邦"),
    "RW": _("卢旺达"),
    "BL": _("圣巴泰勒米"),
    "SH": _("圣赫勒拿,  阿森松和特里斯坦达库尼亚"),
    "KN": _("圣基茨和尼维斯"),
    "LC": _("圣卢西亚"),
    "MF": _("圣马丁(法国)部分"),
    "PM": _("圣皮埃尔和密克隆群岛"),
    "VC": _("圣文森特和格林纳丁斯"),
    "WS": _("萨摩亚"),
    "SM": _("圣马力诺"),
    "ST": _("圣多美和普林西比"),
    "SA": _("沙特阿拉伯"),
    "SN": _("塞内加尔"),
    "RS": _("塞尔维亚"),
    "SC": _("塞舌尔"),
    "SL": _("塞拉利昂"),
    "SG": _("新加坡"),
    "SX": _("荷属圣马丁"),
    "SK": _("斯洛伐克"),
    "SI": _("斯洛文尼亚"),
    "SB": _("所罗门群岛"),
    "SO": _("索马里"),
    "ZA": _("南非"),
    "GS": _("南乔治亚和南桑威奇群岛"),
    "SS": _("南苏丹"),
    "ES": _("西班牙"),
    "LK": _("斯里兰卡"),
    "SD": _("苏丹"),
    "SR": _("苏里南"),
    "SJ": _("斯瓦尔巴群岛和扬马延岛"),
    "SZ": _("斯威士兰"),
    "SE": _("瑞典"),
    "CH": _("瑞士"),
    "SY": _("阿拉伯叙利亚共和国"),
    "TW": _("台湾(中国)"),
    "TJ": _("塔吉克斯坦"),
    "TZ": _("坦桑尼亚联合共和国"),
    "TH": _("泰国"),
    "TL": _("东帝汶"),
    "TG": _("多哥"),
    "TK": _("托克劳"),
    "TO": _("汤加"),
    "TT": _("特立尼达和多巴哥"),
    "TN": _("突尼斯"),
    "TR": _("土耳其"),
    "TM": _("土库曼斯坦"),
    "TC": _("特克斯和凯科斯群岛"),
    "TV": _("图瓦卢"),
    "UG": _("乌干达"),
    "UA": _("乌克兰"),
    "AE": _("阿拉伯联合酋长国"),
    "GB": _("大不列颠及北爱尔兰联合王国"),
    "UM": _("美国小洋屿"),
    "US": _("美利坚合众国"),
    "UY": _("乌拉圭"),
    "UZ": _("乌兹别克斯坦"),
    "VU": _("瓦努阿图"),
    "VE": _("委内瑞拉玻利瓦尔共和国"),
    "VN": _("越南"),
    "VG": _("维尔京群岛(英国)"),
    "VI": _("维尔京群岛(美国)"),
    "WF": _("瓦利斯群岛和富图纳群岛"),
    "EH": _("西撒哈拉"),
    "YE": _("也门"),
    "ZM": _("赞比亚"),
    "ZW": _("津巴布韦"),
}

LANGUAGES_C = (
    ('af', _(u"南非荷兰语")),
    ('ar', _(u"阿拉伯语")),
    ('ast', _(u"阿斯图里亚斯语")),
    ('az', _(u"阿塞拜疆语")),
    ('be', _(u"白俄罗斯语")),
    ('bg', _(u"保加利亚语")),
    ('bn', _(u"孟加拉语")),
    ('br', _(u"布列塔尼语")),
    ('bs', _(u"波斯尼亚语")),
    ('ca', _(u"加泰罗尼亚语")),
    ('cs', _(u"捷克语")),
    ('cy', _(u"威尔士语")),
    ('da', _(u"丹麦语")),
    ('de', _(u"德语")),
    ('dsb', _(u"下索布族语")),
    ('el', _(u"希腊语")),
    ('en', _(u"英语")),
    ('en-au', _(u"澳大利亚英语")),
    ('en-gb', _(u"英式英语")),
    ('eo', _(u"世界语")),
    ('es', _(u"西班牙语")),
    ('es-ar', _(u"阿根廷西班牙语")),
    ('es-co', _(u"哥伦比亚西班牙语")),
    ('es-mx', _(u"墨西哥西班牙语")),
    ('es-ni', _(u"尼加拉瓜语西班牙语")),
    ('es-ve', _(u"委内瑞拉西班牙语")),
    ('et', _(u"爱沙尼亚语")),
    ('eu', _(u"巴斯克")),
    ('fa', _(u"波斯语")),
    ('fi', _(u"芬兰语")),
    ('fr', _(u"法语")),
    ('fy', _(u"弗里斯兰语")),
    ('ga', _(u"爱尔兰语")),
    ('gd', _(u"苏格兰盖尔语")),
    ('gl', _(u"加利西亚语")),
    ('he', _(u"希伯来语")),
    ('hi', _(u"印地语")),
    ('hr', _(u"克罗地亚语")),
    ('hsb', _(u"上索布族语")),
    ('hu', _(u"匈牙利语")),
    ('ia', _(u"国际语")),
    ('id', _(u"印度尼西亚")),
    ('io', _(u"伊多语")),
    ('is', _(u"	冰岛语")),
    ('it', _(u"意大利语")),
    ('ja', _(u"日语")),
    ('ka', _(u"格鲁吉亚语")),
    ('kk', _(u"哈萨克语")),
    ('km', _(u"高棉语")),
    ('kn', _(u"卡纳达语")),
    ('ko', _(u"韩语")),
    ('lb', _(u"卢森堡语")),
    ('lt', _(u"立陶宛语")),
    ('lv', _(u"拉脱维亚语")),
    ('mk', _(u"马其顿语")),
    ('ml', _(u"马拉雅拉姆语")),
    ('mn', _(u"蒙古语")),
    ('mr', _(u"马拉提语")),
    ('my', _(u"缅甸语")),
    ('nb', _(u"挪威布克莫尔语")),
    ('ne', _(u"尼泊尔语")),
    ('nl', _(u"荷兰语")),
    ('nn', _(u"新挪威语")),
    ('no', _(u"挪威语")),
    ('os', _(u"奥塞梯语")),
    ('pa', _(u"旁遮普语")),
    ('pl', _(u"波兰语")),
    ('pt', _(u"葡萄牙语")),
    ('pt-br', _(u"巴西葡萄牙语")),
    ('ro', _(u"罗马尼亚语")),
    ('ru', _(u"俄语")),
    ('sk', _(u"斯洛伐克语")),
    ('sl', _(u"斯洛文尼亚语")),
    ('sq', _(u"阿尔巴尼亚语")),
    ('sr', _(u"塞尔维亚语")),
    ('sr-latn', _(u"塞尔维亚拉丁语")),
    ('sv', _(u"瑞典语")),
    ('sw', _(u"斯瓦希里语")),
    ('ta', _(u"泰米尔语")),
    ('te', _(u"泰卢固语")),
    ('th', _(u"泰語")),
    ('tr', _(u"土耳其语")),
    ('tt', _(u"塔塔尔语")),
    ('udm', _(u"乌德穆尔特语")),
    ('uk', _(u"乌克兰语")),
    ('ur', _(u"乌尔都语")),
    ('vi', _(u"越南语")),
    ('zh-cn', _(u"简体中文")),
    ('zh-hans', _(u"简体中文")),
    ('zh-hant', _(u"繁体中文")),
    ('zh-hk', _(u"繁体中文")),
    ('zh-mo', _(u"繁体中文")),
    ('zh-my', _(u"简体中文")),
    ('zh-sg', _(u"简体中文")),
    ('zh-tw', _(u"繁体中文")),
)
